# Generated by Django 6.0.3 on 2026-03-14 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fragmentoArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('nodo', models.CharField(max_length=50)),
                ('fragmento', models.CharField(max_length=50)),
                ('ruta', models.TextField()),
            ],
        ),
    ]
